name: Java CI with Gradle

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: |
          cd tenta-server
          chmod +x gradlew

      - name: Build with Gradle
        run: |
          cd tenta-server
          ./gradlew build

      - name: Run Tests
        if: success()
        run: |
          cd tenta-server
          ./gradlew test

      - name: Slack Success Message
        if: success()
        uses: tokorom/action-slack-incoming-webhook@v1.1.3
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: :짠:Gradle Unit Test Success:짠:.
          attachments: |
            [
              {
                “color”: “good”,
                “author_name”: “${{ github.actor }}“,
                “author_icon”: “${{ github.event.sender.avatar_url }}“,
                “fields”: [
                  {
                    “title”: “Author”,
                    “value”: “${{ github.actor }}”
                  },
                  {
                    “title”: “GitHub Pull Request URL”,
                    “value”: “${{ github.event.repository.html_url }}/pull/${{ env.ISSUE_NUMBER }}”
                  }
                ]
              }
            ]

      # Unit Test 실패했을 때 Slack에 Fail Message 보냄
      - name: Slack Fail Message
        if: failure()
        uses: tokorom/action-slack-incoming-webhook@v1.1.3
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: :경광등:Gradle Unit Test Failure:경광등:.
          attachments: |
            [
              {
                “color”: “danger”,
                “author_name”: “${{ github.actor }}“,
                “author_icon”: “${{ github.event.sender.avatar_url }}“,
                “fields”: [
                  {
                    “title”: “Author”,
                    “value”: “${{ github.actor }}”
                  },
                  {
                    “title”: “GitHub Pull Request URL”,
                    “value”: “${{ github.event.repository.html_url }}/pull/${{  env.ISSUE_NUMBER  }}”
                  }
                ]
              }
            ]

      # Unit Test 실패했을 때 PR에 Fail Message 생성
      - name: Write a comment when unit test fails
        uses: actions/github-script@v3
        if: failure()
        with:
          github-token: ${{ secrets.API_ACCESS_TOKEN }}
          script: |
            const ref = “${{github.ref}}”
            const pull_number = Number(ref.split(“/”)[2])
            await github.issues.createComment({
              issue_number: pull_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ‘Test Code Fail:손인사: ’
            })